openapi: 3.0.2
info:
  title: Short URL API
  version: "1.0"
servers:
  - url: http://localhost:8080

paths:
  /url:
    get:
      summary: 一覧
      description: 一覧を取得する
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                      $ref: '#/components/schemas/LinkResponse'
    post:
      summary: 登録
      description: 短縮URLを発行する
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LinkResponse'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                original:
                  type: string
                  description: Maximum 2000 characters.
              required:
                - original
    parameters:
      - $ref: '#/components/parameters/AcceptHeader'

components:
  # Paramegers
  parameters:
    AcceptHeader:
      name: accept
      in: header
      description: Request header for content type
      required: false
      schema:
        type: string
        enum:
          - application/json
        default: application/json
  schemas:
    LinkResponse:
      type: object
      properties:
        short:
          type: string
          format: uri
        original:
          type: string
          format: uri
      required:
        - id
        - short
        - original
        - createdAt
        - updatedAt

        

        
