CREATE TABLE links (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(255) NOT NULL UNIQUE,
  original TEXT NOT NULL,
  length INT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
);
